var name =prompt ('ismingiz ?')
var familiya = prompt('familiyangiz ?')
var age =prompt ('yoshingiz?')
var theWork=prompt('ishingiz ?')
var uqishi =prompt('qayerda talim olgan siz ?')
var maosh =prompt('qancha maosh istaysiz?')
var ishKonik =prompt('necha yillik tajribaga egasiz ?')

console.log('ismi:',name)
console.log('familiya:',familiya)
console.log('yoshi:',age)
console.log('ishi:',theWork)
console.log('uqiganjoy:',uqishi)
console.log('maoshIstaydi:',maosh)
console.log('tajriba:',ishKonik)
